### ISSUE TITLE
privileged private registry

### ISSUE THREAD

**Issue by davidzuluagae** [kenzanlabs/kubernetes-ci-cd#49] opened 2018-07-23 21:21 UTC
Private docker registry deployment requires privileged access in order to Read/Write Docker.sock shared as a volume from the host

Temporary workaround:
`chmod 666 /var/run/docker.sock` directly on host

**Comment by mdurandjr** [comment] 2018-08-09 13:33
I was not able to reproduce this issue in my running environment. All services are running as root and have access to /var/run/docker.sock. The only modifications I made to my environment were to update to kubernetes 1.11.0 in the part1.yml file. socat ran without issues.

**Comment by davidzuluagae** [comment] 2018-08-09 15:29
We need to explicit make the necessary changes to ensure that minikube runs docker container runtime and not rkt

**Comment by mdurandjr** [comment] 2018-08-10 18:05
Fixed with PR #81 81

**Closed by mdurandjr** 2018-08-10 18:05 UTC
Labels: PART1
